using AIMS.Core.Entities;
using AIMS.Infrastructure.FileTransfer;
using AIMS.Infrastructure.Services;
using AIMS.SharedKernel.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace AIMS.WebFrontend.Pages.AssetItems;

[Authorize(Roles = "Admin,Manager")]
public class EditModel : PageModel
{
    private readonly AssetItemService _assetItemService;
    private readonly PlantService _plantService;
    private readonly IActivityLogger _activityLogger;
    private readonly IWebHostEnvironment _env;
    private readonly FileUploadHelper _fileUpload;

    public EditModel(AssetItemService assetItemService, PlantService plantService, IActivityLogger activityLogger, IWebHostEnvironment env, FileUploadHelper fileUpload)
    {
        _assetItemService = assetItemService;
        _plantService = plantService;
        _activityLogger = activityLogger;
        _env = env;
        _fileUpload = fileUpload;
    }

    [BindProperty]
    public EditAssetItemInput Input { get; set; } = new();

    /// <summary>Current persisted Asset Tag No., shown read-only; regenerated by the service on save.</summary>
    public string? CurrentAssetId { get; set; }
    public string? CurrentPicturePath { get; set; }
    public int AssetItemId { get; set; }

    public List<EquipmentCode> EquipmentCodes => EquipmentCode.All.ToList();
    public List<CivilAssetCode> CivilAssetCodes => CivilAssetCode.All.ToList();
    public List<Plant> Plants { get; set; } = new();

    public async Task<IActionResult> OnGetAsync(int id)
    {
        var assetItem = await _assetItemService.GetByIdAsync(id);
        if (assetItem == null) return NotFound();

        AssetItemId = id;
        Plants = await _plantService.ListAsync();
        CurrentAssetId = assetItem.AssetId;
        CurrentPicturePath = assetItem.PicturePath;
        Input = new EditAssetItemInput
        {
            PlantId = assetItem.PlantId,
            GisRefNo = assetItem.GisRefNo,
            Title = assetItem.Title,
            EquipmentCode = assetItem.EquipmentCode,
            EquipmentDesc = assetItem.EquipmentDesc,
            CivilAssetCode = assetItem.CivilAssetCode,
            CivilAssetDesc = assetItem.CivilAssetDesc,
            CivilAssetOrder = assetItem.CivilAssetOrder,
            Function = assetItem.Function,
            Material = assetItem.Material,
            YearInstalled = assetItem.YearInstalled,
            Owner = assetItem.Owner,
            Constrain = assetItem.Constrain,
            Access = assetItem.Access,
            CoordinateN = assetItem.CoordinateN,
            CoordinateE = assetItem.CoordinateE,
            Zone = assetItem.Zone,
            Area = assetItem.Area,
            Train = assetItem.Train,
            Category = assetItem.Category
        };

        return Page();
    }

    public async Task<IActionResult> OnPostAsync(int id)
    {
        var assetItem = await _assetItemService.GetByIdAsync(id);
        if (assetItem == null) return NotFound();

        AssetItemId = id;
        Plants = await _plantService.ListAsync();
        CurrentAssetId = assetItem.AssetId;
        CurrentPicturePath = assetItem.PicturePath;

        if (!ModelState.IsValid) return Page();

        var picturePath = assetItem.PicturePath;
        var newPictureSaved = false;
        if (Input.Picture != null && Input.Picture.Length > 0)
        {
            var (isValid, error) = _fileUpload.ValidatePicture(Input.Picture);
            if (!isValid)
            {
                ModelState.AddModelError("Input.Picture", error);
                return Page();
            }
            picturePath = await _fileUpload.SaveAssetPictureAsync(Input.Picture, _env.WebRootPath);
            newPictureSaved = true;
            // The old picture is deliberately left in place until the update below
            // succeeds — if the update is refused, no file is lost.
        }

        var equipDesc = EquipmentCode.GetDescription(Input.EquipmentCode);
        var civilDesc = CivilAssetCode.GetDescription(Input.CivilAssetCode);

        // AssetId (Asset Tag No.) is regenerated server-side by AssetItemService from
        // Plant/Equipment/Civil codes — it is never accepted as client input.
        var updates = new AssetItem
        {
            GisRefNo = Input.GisRefNo,
            Title = Input.Title,
            EquipmentCode = Input.EquipmentCode,
            EquipmentDescription = equipDesc,
            EquipmentDesc = Input.EquipmentDesc,
            CivilAssetCode = Input.CivilAssetCode,
            CivilAssetDescription = civilDesc,
            CivilAssetDesc = Input.CivilAssetDesc,
            CivilAssetOrder = Input.CivilAssetOrder,
            Function = Input.Function,
            Material = Input.Material,
            YearInstalled = Input.YearInstalled,
            Owner = Input.Owner,
            Constrain = Input.Constrain,
            Access = Input.Access,
            CoordinateN = Input.CoordinateN,
            CoordinateE = Input.CoordinateE,
            Zone = Input.Zone,
            Area = Input.Area,
            Train = Input.Train,
            Category = Input.Category,
            // Condition (GVI) & Inspection fields are owned by the dedicated Condition
            // tab (EditCondition.cshtml) — carry them over unchanged so this page's
            // full-row UPDATE doesn't clobber that data.
            DateOfInspection = assetItem.DateOfInspection,
            Inspector = assetItem.Inspector,
            Condition = assetItem.Condition,
            Comment = assetItem.Comment,
            PicturePath = picturePath,
            PlantId = Input.PlantId
        };

        try
        {
            await _assetItemService.UpdateAsync(id, updates);
        }
        catch (DuplicateAssetIdException ex)
        {
            // The regenerated tag already belongs to another asset — discard the
            // replacement picture staged above; the old one is still on disk and still
            // referenced by the DB, so the form re-renders with no data lost.
            if (newPictureSaved)
                _fileUpload.DeleteFile(picturePath!, _env.WebRootPath);
            ModelState.AddModelError(string.Empty, ex.Message);
            return Page();
        }

        // Update committed — only now is it safe to drop the superseded picture.
        if (newPictureSaved && !string.IsNullOrEmpty(assetItem.PicturePath))
            _fileUpload.DeleteFile(assetItem.PicturePath, _env.WebRootPath);

        await _activityLogger.LogActivityAsync(
            "AssetItemUpdated",
            $"Asset item '{assetItem.Title}' updated to '{Input.Title}'",
            "AssetItem",
            id.ToString());

        return RedirectToPage("Index");
    }

    public class EditAssetItemInput
    {
        [Display(Name = "Plant")]
        public int? PlantId { get; set; }

        [StringLength(200)] public string? GisRefNo { get; set; }

        [Required, StringLength(200)] public string Title { get; set; } = string.Empty;

        [Required, StringLength(200)] public string EquipmentCode { get; set; } = string.Empty;

        [StringLength(200)] public string? EquipmentDesc { get; set; }

        [Required, StringLength(200)] public string CivilAssetCode { get; set; } = string.Empty;

        [StringLength(200)] public string? CivilAssetDesc { get; set; }
        public int? CivilAssetOrder { get; set; }

        [StringLength(200)] public string? Function { get; set; }
        [StringLength(200)] public string? Material { get; set; }
        public int? YearInstalled { get; set; }

        [StringLength(200)] public string? Owner { get; set; }
        [StringLength(200)] public string? Constrain { get; set; }
        [StringLength(200)] public string? Access { get; set; }

        [StringLength(200)] public string? CoordinateN { get; set; }
        [StringLength(200)] public string? CoordinateE { get; set; }

        [StringLength(200)] public string? Zone { get; set; }
        [StringLength(200)] public string? Area { get; set; }
        [StringLength(200)] public string? Train { get; set; }
        [StringLength(250)] public string? Category { get; set; }

        public IFormFile? Picture { get; set; }
    }
}
