using AIMS.Core.Entities;
using AIMS.Infrastructure.FileTransfer;
using AIMS.Infrastructure.Services;
using AIMS.SharedKernel.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace AIMS.WebFrontend.Pages.AssetItems;

[Authorize(Roles = "Admin,Manager")]
public class EditModel : PageModel
{
    private readonly AssetItemService _assetItemService;
    private readonly PlantService _plantService;
    private readonly IActivityLogger _activityLogger;
    private readonly IWebHostEnvironment _env;
    private readonly FileUploadHelper _fileUpload;

    public EditModel(AssetItemService assetItemService, PlantService plantService, IActivityLogger activityLogger, IWebHostEnvironment env, FileUploadHelper fileUpload)
    {
        _assetItemService = assetItemService;
        _plantService = plantService;
        _activityLogger = activityLogger;
        _env = env;
        _fileUpload = fileUpload;
    }

    [BindProperty]
    public EditAssetItemInput Input { get; set; } = new();

    public string? ExistingPicturePath { get; set; }

    /// <summary>Current persisted Asset Tag No., shown read-only; regenerated by the service on save.</summary>
    public string? CurrentAssetId { get; set; }

    public List<EquipmentCode> EquipmentCodes => EquipmentCode.All.ToList();
    public List<CivilAssetCode> CivilAssetCodes => CivilAssetCode.All.ToList();
    public List<Plant> Plants { get; set; } = new();

    public async Task<IActionResult> OnGetAsync(int id)
    {
        var assetItem = await _assetItemService.GetByIdAsync(id);
        if (assetItem == null) return NotFound();

        Plants = await _plantService.ListAsync();
        ExistingPicturePath = assetItem.PicturePath;
        CurrentAssetId = assetItem.AssetId;
        Input = new EditAssetItemInput
        {
            PlantId = assetItem.PlantId,
            GisRefNo = assetItem.GisRefNo,
            Title = assetItem.Title,
            EquipmentCode = assetItem.EquipmentCode,
            EquipmentDesc = assetItem.EquipmentDesc,
            EquipmentOrder = assetItem.EquipmentOrder,
            CivilAssetCode = assetItem.CivilAssetCode,
            CivilAssetDesc = assetItem.CivilAssetDesc,
            CivilAssetOrder = assetItem.CivilAssetOrder,
            QrCode = assetItem.QrCode,
            Function = assetItem.Function,
            Material = assetItem.Material,
            YearInstalled = assetItem.YearInstalled,
            Owner = assetItem.Owner,
            Constrain = assetItem.Constrain,
            Access = assetItem.Access,
            CoordinateN = assetItem.CoordinateN,
            CoordinateE = assetItem.CoordinateE,
            Zone = assetItem.Zone,
            Area = assetItem.Area,
            Train = assetItem.Train,
            DateOfInspection = assetItem.DateOfInspection,
            Inspector = assetItem.Inspector,
            Condition = assetItem.Condition,
            Comment = assetItem.Comment
        };

        return Page();
    }

    public async Task<IActionResult> OnPostAsync(int id)
    {
        var assetItem = await _assetItemService.GetByIdAsync(id);
        if (assetItem == null) return NotFound();

        Plants = await _plantService.ListAsync();
        ExistingPicturePath = assetItem.PicturePath;
        CurrentAssetId = assetItem.AssetId;

        if (!ModelState.IsValid) return Page();

        string? newPicturePath = assetItem.PicturePath;

        if (Input.Picture != null && Input.Picture.Length > 0)
        {
            var (isValid, error) = _fileUpload.ValidatePicture(Input.Picture);
            if (!isValid)
            {
                ModelState.AddModelError("Input.Picture", error);
                return Page();
            }

            _fileUpload.DeleteFile(assetItem.PicturePath, _env.WebRootPath);
            newPicturePath = await _fileUpload.SaveAssetPictureAsync(Input.Picture, _env.WebRootPath);
        }

        var equipDesc = EquipmentCode.GetDescription(Input.EquipmentCode);
        var civilDesc = CivilAssetCode.GetDescription(Input.CivilAssetCode);

        // AssetId (Asset Tag No.) is regenerated server-side by AssetItemService from
        // Plant/Equipment/Civil codes — it is never accepted as client input.
        var updates = new AssetItem
        {
            GisRefNo = Input.GisRefNo,
            Title = Input.Title,
            EquipmentCode = Input.EquipmentCode,
            EquipmentDescription = equipDesc,
            EquipmentDesc = Input.EquipmentDesc,
            EquipmentOrder = Input.EquipmentOrder,
            CivilAssetCode = Input.CivilAssetCode,
            CivilAssetDescription = civilDesc,
            CivilAssetDesc = Input.CivilAssetDesc,
            CivilAssetOrder = Input.CivilAssetOrder,
            QrCode = Input.QrCode,
            Function = Input.Function,
            Material = Input.Material,
            YearInstalled = Input.YearInstalled,
            Owner = Input.Owner,
            Constrain = Input.Constrain,
            Access = Input.Access,
            CoordinateN = Input.CoordinateN,
            CoordinateE = Input.CoordinateE,
            Zone = Input.Zone,
            Area = Input.Area,
            Train = Input.Train,
            DateOfInspection = Input.DateOfInspection,
            Inspector = Input.Inspector,
            Condition = Input.Condition,
            Comment = Input.Comment,
            PicturePath = newPicturePath,
            PlantId = Input.PlantId
        };

        await _assetItemService.UpdateAsync(id, updates);

        await _activityLogger.LogActivityAsync(
            "AssetItemUpdated",
            $"Asset item '{assetItem.Title}' updated to '{Input.Title}'",
            "AssetItem",
            id.ToString());

        return RedirectToPage("Index");
    }

    public class EditAssetItemInput
    {
        [Display(Name = "Plant")]
        public int? PlantId { get; set; }

        [StringLength(200)] public string? GisRefNo { get; set; }

        [Required, StringLength(200)] public string Title { get; set; } = string.Empty;

        [Required, StringLength(200)] public string EquipmentCode { get; set; } = string.Empty;

        [StringLength(200)] public string? EquipmentDesc { get; set; }
        public int? EquipmentOrder { get; set; }

        [Required, StringLength(200)] public string CivilAssetCode { get; set; } = string.Empty;

        [StringLength(200)] public string? CivilAssetDesc { get; set; }
        public int? CivilAssetOrder { get; set; }

        [StringLength(500)] public string? QrCode { get; set; }

        [StringLength(200)] public string? Function { get; set; }
        [StringLength(200)] public string? Material { get; set; }
        public int? YearInstalled { get; set; }

        [StringLength(200)] public string? Owner { get; set; }
        [StringLength(200)] public string? Constrain { get; set; }
        [StringLength(200)] public string? Access { get; set; }

        [StringLength(200)] public string? CoordinateN { get; set; }
        [StringLength(200)] public string? CoordinateE { get; set; }

        [StringLength(200)] public string? Zone { get; set; }
        [StringLength(200)] public string? Area { get; set; }
        [StringLength(200)] public string? Train { get; set; }

        public DateTime? DateOfInspection { get; set; }
        [StringLength(200)] public string? Inspector { get; set; }
        [StringLength(200)] public string? Condition { get; set; }
        [StringLength(1000)] public string? Comment { get; set; }

        public IFormFile? Picture { get; set; }
    }
}
